import tkinter as tk
from tkinter import Text, Button, END
import requests

def chat_with_ai(question):
    """
    This function sends a GET request to the ChatGPT API with the provided question
    as a parameter. It expects a JSON response containing an "answer" key, which
    holds the generated answer from the AI. If the API request is successful, it returns
    the answer. If the request fails, it returns an error message indicating the HTTP
    status code.

    Args:
        question (str): The question to be asked to the AI.

    Returns:
        str: The answer generated by the AI, or an error message if the API request fails.
    """
    # Define the base URL of the ChatGPT API
    api_url = "https://chatgpt.apinepdev.workers.dev/?question="
    
    # Construct the full URL by appending the question to the base URL
    full_url = api_url + question
    
    # Send a GET request to the API with the constructed URL
    response = requests.get(full_url)
    
    # Check if the request was successful (status code 200)
    if response.status_code == 200:
        # If the request was successful, extract the JSON response
        data = response.json()
        
        # Extract the "answer" key from the JSON response
        answer = data.get("answer", "No answer available.")
        
        # Return the answer
        return answer
    else:
        # If the request failed, return an error message indicating the status code
        return "Error: " + str(response.status_code)

def send_question():
    question = question_entry.get("1.0", END).strip()
    if question.lower() == 'exit':
        window.destroy()
    else:
        answer = chat_with_ai(question)
        answer_text.configure(state="normal")
        answer_text.insert(END, "Answer: " + answer + "\n\n", "answer")
        answer_text.configure(state="disabled")
        question_entry.delete("1.0", END)
        question_entry.focus()

# Graphical User Interface
def create_gui():
    global window
    window = tk.Tk()
    window.title("ChatGPT")
    window.configure(bg="gray")
    window.geometry("600x800")

    prompt_label = tk.Label(window, text="Ask me anything!", font=("Helvetica", 20), bg="gray", fg="black")
    prompt_label.pack(pady=10)

    global question_entry
    question_entry = Text(window, width=40, height=3, bg="darkgray", fg="black")
    question_entry.pack(pady=10)

    global answer_text
    answer_text = Text(window, width=80, height=30, bg="black", fg="green")
    answer_text.tag_configure("answer", foreground="white")
    answer_text.configure(state="disabled")
    answer_text.pack(pady=10)

    send_button = Button(window, text="Send", command=send_question, bg="gray", fg="black")
    send_button.pack(side=tk.RIGHT, padx=10, pady=10)

    exit_button = Button(window, text="Exit", command=window.destroy, bg="gray", fg="black")
    exit_button.pack(side=tk.RIGHT, padx=10, pady=10)

    window.mainloop()

if __name__ == "__main__":
    create_gui()
